server:
  port: 8080
  servlet:
    context-path: /

spring:
#数据源连接配置
  datasource:
    name: test
    type: com.alibaba.druid.pool.DruidDataSource
    druid: #druid相关配置
      url: jdbc:mysql://localhost:3306/nj_1802_pro?serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: hanchun123
      #监控统计拦截的filters
      filters: stat
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20  
    
 
 #整合myBatis
mybatis:
  mapper-locations: classpath:com/qfjy/mapper/*.xml   # mapper映射对应的配置文件位置.xml
  type-aliases-package: com.qfjy.bean        # 对应的实体类的包名
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #这个是可以打印sql、参数、查询结果的
                                                             # org.apache.ibatis.logging.log4j.Log4jImpl:这个不打印查询结果
